services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    command: npm run start:dev
    networks:
      - default
      - db_default

networks:
  db_default:
    external: true
