services:
  - type: web
    name: ghostroom-backend
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ghostroom-redis
          property: connectionString

  - type: redis
    name: ghostroom-redis
    plan: free
    ipAllowList: [] # Only allow internal connections
